MOTIVO DEL COMMIT: Arreglar algunos hooks, IMPLEMENTACIÓN: Arreglados los hooks comentados para que estén disponbiles para todos los miembros

diff --git a/gitHooks/pre-commit b/gitHooks/pre-commit
--- a/gitHooks/pre-commit
+++ b/gitHooks/pre-commit
@@ -5,21 +5,21 @@
 changed_files=$(git diff --cached --name-only --diff-filter=ACM)
 correcto=false
 # Función para verificar caracteres no ASCII
-# check_for_non_ascii_characters() {
-#     file=$1
-#     if [[ $(grep -P -n -o "[^\x00-\x7F]" "$file") ]]; then
-#         echo "Error: El archivo $file contiene caracteres no ASCII."
-#         exit 1
-#     fi
-# }
+check_for_non_ascii_characters() {
+    file=$1
+    if [[ $(grep -P -n -o "[^\x00-\x7F]" "$file") ]]; then
+        echo "Error: El archivo $file contiene caracteres no ASCII."
+        exit 1
+    fi
+}
 
-# # Verificar caracteres en archivos modificados
-# for file in $changed_files; do
-#     if [ -f "$file" ]; then
-#         check_for_non_ascii_characters "$file"
-#     fi
+# Verificar caracteres en archivos modificados
+for file in $changed_files; do
+    if [ -f "$file" ]; then
+        check_for_non_ascii_characters "$file"
+    fi
 
-# done
+done
 
 echo "Todos los archivos pasaron la verificación de caracteres ASCII."
 correcto=true
